#!/bin/bash
### BEGIN INIT INFO
# Provides: startserver
# Required-Start:    $all
# Required-Stop: 
# Default-Start:     5 
# Default-Stop:      6 
# Short-Description: start nodejs server
### END INIT INFO

/home/updateProject.sh
 