#!/bin/bash
### BEGIN INIT INFO
# Provides: startserver
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: start nodejs server
### END INIT INFO

DAEMON="/var/mongo/import_sgbd.sh" #ligne de commande du programme, attention à l'extension .py.
DAEMONUSER="root" #utilisateur du programme
DAEMONNAME="startserver" #Nom du programme (doit être identique à l'exécutable).

d_start () {
    /var/mongo/import_sgbd.sh
}
 
d_stop () {
    /var/mongo/import_sgbd.sh
}
 
d_restart () {
    d_stop
    d_start
}
 
case "$1" in
    start|stop)
        d_${1}
        ;;
 
    restart|reload)
        d_restart
        ;;

    *)
        echo "Usage: /etc/init.d/$DAEMONNAME {start|stop|restart|reload}"
        ;;
esac

exit 0
