
services:
###########################
# Setup the nodejs container
###########################
    nodejs:
        container_name: ${NAME_PROJECT}_nodejs
        restart: always
        tty: true
        stdin_open: true
        build: 
            context: .docker/nodejs
            args:
                - VALUE_NODEJS_VERSION=${VALUE_NODEJS_VERSION}
                - NAME_PROJECT=${NAME_PROJECT}
                - NAME_JS_SERVER=${NAME_JS_SERVER}
        volumes:
            - ./www/:/home/project/www
            - ./config/data:/var/docker/nodejs/data
            - ./.env:/home/project/www/${FOLDER_CONFIG}/.env:rw
            - ./config/connection_server.json:/home/project/www/${FOLDER_CONFIG}/connection_server.json:rw
            - ./config/connection_mongo.json:/home/project/www/${FOLDER_CONFIG}/connection_mongo.json:rw
            - ./config/config_email.json:/home/project/www/${FOLDER_CONFIG}/config_email.json:rw
            - ./.env:/var/docker/nodejs/.env:rw
            - ./.dockertmp/logs/pm2:/root/.pm2/logs/:rw
            - ./.dockertmp/tmp/nodejs:/var/tmp/nodejs:rw
            - ./.dockertmp/logs/nodejs:/var/log/docker/nodejs/:rw
        environment:
            - TZ=${VALUE_TIMEZONES}
        ports:
            - ${VALUE_NODEJS_PORT}:3000

###########################
# Setup the mongo container
###########################
    mongo:
        #image: mongo:${VALUE_MONGO_VERSION}
        container_name: ${NAME_PROJECT}_mongo
        build: 
            context: .docker/mongo
            args:
                - VALUE_MONGO_VERSION=${VALUE_MONGO_VERSION}
        restart: always
        volumes:
            - ./.env:/var/docker/mongo/.env
            - ./.dockertmp/mongo_data:/data/db
            - ./config/sgbd_data:/docker-entrypoint-initdb.d/:rw
        environment:
            - TZ=${VALUE_TIMEZONES}
            - MONGO_INITDB_DATABASE=${SGBD_DATABASE}
            - MONGO_INITDB_ROOT_USERNAME=${SGBD_USER}
            - MONGO_INITDB_ROOT_PASSWORD=${SGBD_PASSWORD}
        
###########################
# Setup the mongo-express container
###########################
    mongo-express:
        image: mongo-express:${VALUE_MONGOEXP_VERSION}
        container_name: ${NAME_PROJECT}_moexpress
        restart: always
        environment:
            - ME_CONFIG_MONGODB_SERVER=${NAME_PROJECT}_mongo
            - ME_CONFIG_MONGODB_ADMINUSERNAME=${SGBD_USER}
            - ME_CONFIG_MONGODB_ADMINPASSWORD=${SGBD_PASSWORD}
            - ME_CONFIG_BASICAUTH_USERNAME=${SGBD_USER}
            - ME_CONFIG_BASICAUTH_PASSWORD=${SGBD_PASSWORD}
            - ME_CONFIG_BASICAUTH=false
            - ME_CONFIG_MONGODB_URL=mongodb://${SGBD_USER}:${SGBD_PASSWORD}@${NAME_PROJECT}_mongo:27017/?authSource=${SGBD_USER}
        depends_on:
            - mongo
        ports:
            - ${VALUE_MONGOEXP_PORT}:8081
        
###########################
# Setup the mailhog container
###########################
    mailhog:
        image: mailhog/mailhog:${VALUE_MAILHOG_VERSION}
        container_name: ${NAME_PROJECT}_mailhog
        restart: always
        ports:
            - ${VALUE_MAILHOG_PORT}:8025
